name: Daily Build

on:
  push:
  schedule:
    - cron: '0 18 * * *' # Runs at 00:00 UTC every day

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py
      run: |
        python main.py

    - name: Get the date
      id: get-date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Sign File
      run: |
        gpg --batch --yes --detach-sign --armor --output holiday_cn_zh-cn.sig holiday_cn_zh-cn

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        files: |
          holiday_cn_zh-cn
          holiday_cn_zh-cn.sig
        tag_name: ${{ steps.get-date.outputs.today }}
        release_name: Release ${{ steps.get-date.outputs.today }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
