name: Daily Build

on:
  push:
  schedule:
    - cron: '0 18 * * *' # Runs at 00:00 UTC every day

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py
      run: |
        python main.py

    - name: Download latest release file
      id: download
      uses: wei/curl@master
      with:
        args: -L https://github.com/0xcccccccccccc/kholidays_cn/releases/latest/download/holiday_cn_zh-cn -o latest_holiday_cn_zh-cn

    - name: Compare files (ignoring the first 8 lines)
      id: compare
      run: |
        if cmp <(tail -n +9 holiday_cn_zh-cn) <(tail -n +9 latest_holiday_cn_zh-cn); then
          echo "Files are identical after ignoring the first 8 lines, skipping release."
          echo "skip=true" >> $GITHUB_ENV
        else
          echo "Files differ after ignoring the first 8 lines, proceeding with release."
          echo "skip=false" >> $GITHUB_ENV
        fi

    - name: Get the date
      if: env.skip == 'false'
      run: |
        echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: env.skip == 'false'
      with:
        files: holiday_cn_zh-cn
        tag_name: ${{ env.today }}
        release_name: Release ${{ env.today }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}